apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app.env }}-{{ .Values.app.component }}-{{ .Values.app.type }}-job-{{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum | trunc 12 }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
      - name: runner
        image: {{ .Values.job.image }}
        command:
          - sh
          - -c
          - |
            echo "Printing lines in UPPERCASE:"
            cat /config/lines.txt | while read line; do
              echo "$line" | tr '[:lower:]' '[:upper:]'
            done
        volumeMounts:
        - name: config
          mountPath: /config
      restartPolicy: Never
    volumes:
      - name: config
        configMap:
          name: {{ .Values.app.env }}-{{ .Values.app.component }}-{{ .Values.app.type }}-cm